on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  nixbuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-suffix: ["", "-aarch64"]

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - uses: cachix/cachix-action@v12
      with:
        name: beni
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        cachixArgs: "-j8 -c16"
        pushFilter: "(-source$|nixpkgs\\.tar\\.gz$|rust|cargo|mkDummySrc$)"

    - run: nix flake show
    - run: nix build .#default${{ matrix.target-suffix }}
    - run: nix build .#docker${{ matrix.target-suffix }}
    - run: nix build .#musl${{ matrix.target-suffix }}

    - uses: actions/upload-artifact@v3
      with:
        name: netbench-linux${{ matrix.target-suffix }}
        path: result/bin/netbench
        if-no-files-found: error

  dockerhub:
    runs-on: ubuntu-latest
    needs: nixbuild
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - uses: cachix/cachix-action@v12
      with:
        name: beni
        skipPush: true
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: nix run .#dockerTag

  winbuild:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install rust
      run: rustup toolchain install stable
    - run: cargo build --verbose --release
    - uses: actions/upload-artifact@v3
      with:
        name: netbench-windows-x86_64
        path: target/release/netbench.exe
        if-no-files-found: error
